server:
  port: 8080

spring:
  application:
    name: marketplace-backend

  datasource:
    url: jdbc:postgresql://localhost:5432/marketplace
    username: BenNeji
    password: BenNeji
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

jwt:
  secret: "replace-with-64+random-chars-for-HS256"
  expiration: 36000000